<a href="https://colab.research.google.com/github/ayushiiii28/Meta-Scifor/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NumPy is a Python library used for working with arrays.
#It also has functions for working in domain of linear algebra, fourier transform, and matrices
import numpy as np


In [3]:
import numpy as np
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals'

In [4]:
import numpy as np
np.sqrt(10) # sqrt=square root

3.1622776601683795

In [6]:
print("Maximum ",np.amax([1,2,3,4,5]))
print("Minimum ",np.amin([1,2,3,4,5]))

Maximum  5
Minimum  1


In [9]:
#rounding off a number
import numpy as np
from numpy import ceil
print(np,ceil(3.14))

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'> 4.0


In [10]:
np.ceil(np.sum(np.sqrt([5,10,15])))

10.0

In [11]:
np.array([5,9,13])

array([ 5,  9, 13])

In [13]:
xyz=np.array([1,2,3,4])
print(xyz)

[1 2 3 4]


In [14]:
type(xyz)

numpy.ndarray

In [15]:
a=np.array([[1,2],[3,4],[4,5]])
print("Type - ",a.dtype)

print("\n",a)

Type -  int64

 [[1 2]
 [3 4]
 [4 5]]


In [16]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [17]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print("Type : ",type(mat))
print("Here is the marks \n------\n",mat,"\n-----------")
print("dimension: ",mat.ndim)#ndim gives dimension,2 for a matrix and 1 for vector
print("size : ",mat.size)#size shows total number elements
print("Shape  : ",mat.shape)#shape shows how many rows and column
print("Data Type ; ",mat.dtype)#shoes which type

Type :  <class 'numpy.ndarray'>
Here is the marks 
------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----------
dimension:  2
size :  9
Shape  :  (3, 3)
Data Type ;  int64


In [19]:
a=np.arange(10)

In [21]:
np.arange(50,-1,-5)

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [22]:
print(np.linspace(10,40,5))


[10.  17.5 25.  32.5 40. ]


In [23]:
#By default endpoint=True
#Bydefault retstep=False
np.linspace(2.0,3.0,num=4,endpoint=True,retstep=True)


(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [24]:
#Making matrix
print(np.zeros([5,6]))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [25]:
print(5*np.ones([5,6]))

[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


In [26]:
x=np.arange(30).reshape(5,6)
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [27]:
#Random Number Generation
np.random.seed(6) # Each seed number will generate similar data
#Unifrom DIstribution
print(np.random.rand(10,6))

[[0.89286015 0.33197981 0.82122912 0.04169663 0.10765668 0.59505206]
 [0.52981736 0.41880743 0.33540785 0.62251943 0.43814143 0.73588211]
 [0.51803641 0.5788586  0.6453551  0.99022427 0.8198582  0.41320093]
 [0.87626766 0.82375943 0.05447451 0.71863724 0.80217056 0.73640664]
 [0.70913175 0.54093685 0.12482417 0.9576473  0.4032563  0.21695116]
 [0.71727585 0.99420744 0.25561406 0.67130943 0.59900591 0.71733215]
 [0.93734953 0.35180977 0.2536341  0.40247251 0.74651072 0.72407057]
 [0.4061078  0.98937985 0.45049928 0.37380843 0.70962861 0.08245855]
 [0.39837292 0.77088097 0.76475098 0.28385938 0.18954219 0.47125096]
 [0.33480604 0.73473504 0.18910712 0.33110407 0.84422842 0.61502403]]


In [28]:
print(np.random.randn(10,6))
#Normal Distribution

[[-0.37550472  0.39636757 -0.47144628  2.33660781  1.50278553 -0.59545972]
 [ 0.52834106  0.9398248   0.42628539 -0.75815703 -0.16236698  0.72680996]
 [ 0.44408297 -0.85682264  0.44692842 -1.01464799 -2.1323234   0.17386307]
 [ 0.95120126  0.44189739  1.46901739  1.74951635  0.35353062 -0.64333729]
 [-0.04723705 -1.44903979 -0.03618977 -0.09084699  0.17629034  1.09462041]
 [-2.12647459  0.75144883 -0.54060704  0.79322236  0.17365335 -1.03543429]
 [ 0.87426839 -0.73957208  0.52294535 -0.59187648 -0.47748711  0.11252968]
 [ 1.90474232  0.69415315 -0.01958134  1.66284285  0.03060843 -0.29749921]
 [-0.96813764  0.16706673  0.11660197 -0.68225732 -1.91402115 -0.13990231]
 [ 0.11492459 -0.39500464 -0.95331626 -1.07282736 -0.48444561  1.36293786]]


In [29]:
np.random.randint(5,20,10)
#Random Integer

array([ 7, 17,  6, 19, 17, 19, 15, 14,  7,  5])

In [33]:
def generate_otp():
    otp=np.random.randint(1000,10000,1)
    print("Your Otp is ",otp)
    user_otp=int(input("Enter Your OTP Here"))
    if otp==user_otp:
        print("Log in Sucessfully")
    else:
        print("Your OTP is invalid")
generate_otp()

Your Otp is  [3395]
Enter Your OTP Here3432
Your OTP is invalid
